const { ApolloServer, gql } = require('apollo-server-express');
const { makeAugmentedSchema } = require("neo4j-graphql-js");
const driver = require('./db');
const typeDefs = require('../graphql/graphql.schema');


const schema = makeAugmentedSchema({
  typeDefs
});

// Apollo Server will serve our GraphQL API using the schema
// generated by neo4j-graphql-js's makeAugmentedSchema
module.exports =  new ApolloServer({
  context: { driver },
  schema
});
